// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: A.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AClient is the client API for A service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AClient interface {
	HelloA(ctx context.Context, in *AReq, opts ...grpc.CallOption) (*AResp, error)
	// 健康检查
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (A_WatchClient, error)
}

type aClient struct {
	cc grpc.ClientConnInterface
}

func NewAClient(cc grpc.ClientConnInterface) AClient {
	return &aClient{cc}
}

func (c *aClient) HelloA(ctx context.Context, in *AReq, opts ...grpc.CallOption) (*AResp, error) {
	out := new(AResp)
	err := c.cc.Invoke(ctx, "/A/HelloA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/A/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aClient) Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (A_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &A_ServiceDesc.Streams[0], "/A/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &aWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type A_WatchClient interface {
	Recv() (*HealthCheckResponse, error)
	grpc.ClientStream
}

type aWatchClient struct {
	grpc.ClientStream
}

func (x *aWatchClient) Recv() (*HealthCheckResponse, error) {
	m := new(HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AServer is the server API for A service.
// All implementations must embed UnimplementedAServer
// for forward compatibility
type AServer interface {
	HelloA(context.Context, *AReq) (*AResp, error)
	// 健康检查
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Watch(*HealthCheckRequest, A_WatchServer) error
	mustEmbedUnimplementedAServer()
}

// UnimplementedAServer must be embedded to have forward compatible implementations.
type UnimplementedAServer struct {
}

func (UnimplementedAServer) HelloA(context.Context, *AReq) (*AResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloA not implemented")
}
func (UnimplementedAServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAServer) Watch(*HealthCheckRequest, A_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAServer) mustEmbedUnimplementedAServer() {}

// UnsafeAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AServer will
// result in compilation errors.
type UnsafeAServer interface {
	mustEmbedUnimplementedAServer()
}

func RegisterAServer(s grpc.ServiceRegistrar, srv AServer) {
	s.RegisterService(&A_ServiceDesc, srv)
}

func _A_HelloA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AServer).HelloA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/A/HelloA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AServer).HelloA(ctx, req.(*AReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _A_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/A/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AServer).Watch(m, &aWatchServer{stream})
}

type A_WatchServer interface {
	Send(*HealthCheckResponse) error
	grpc.ServerStream
}

type aWatchServer struct {
	grpc.ServerStream
}

func (x *aWatchServer) Send(m *HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

// A_ServiceDesc is the grpc.ServiceDesc for A service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var A_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "A",
	HandlerType: (*AServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloA",
			Handler:    _A_HelloA_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _A_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _A_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "A.proto",
}
