// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: B.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BClient is the client API for B service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BClient interface {
	HelloB(ctx context.Context, in *BReq, opts ...grpc.CallOption) (*BResp, error)
}

type bClient struct {
	cc grpc.ClientConnInterface
}

func NewBClient(cc grpc.ClientConnInterface) BClient {
	return &bClient{cc}
}

func (c *bClient) HelloB(ctx context.Context, in *BReq, opts ...grpc.CallOption) (*BResp, error) {
	out := new(BResp)
	err := c.cc.Invoke(ctx, "/B/HelloB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BServer is the server API for B service.
// All implementations must embed UnimplementedBServer
// for forward compatibility
type BServer interface {
	HelloB(context.Context, *BReq) (*BResp, error)
	mustEmbedUnimplementedBServer()
}

// UnimplementedBServer must be embedded to have forward compatible implementations.
type UnimplementedBServer struct {
}

func (UnimplementedBServer) HelloB(context.Context, *BReq) (*BResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloB not implemented")
}
func (UnimplementedBServer) mustEmbedUnimplementedBServer() {}

// UnsafeBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BServer will
// result in compilation errors.
type UnsafeBServer interface {
	mustEmbedUnimplementedBServer()
}

func RegisterBServer(s grpc.ServiceRegistrar, srv BServer) {
	s.RegisterService(&B_ServiceDesc, srv)
}

func _B_HelloB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BServer).HelloB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/B/HelloB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BServer).HelloB(ctx, req.(*BReq))
	}
	return interceptor(ctx, in, info, handler)
}

// B_ServiceDesc is the grpc.ServiceDesc for B service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var B_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "B",
	HandlerType: (*BServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloB",
			Handler:    _B_HelloB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "B.proto",
}
